name: Perforce Klocwork scan cpp

on:
  push:
    branches:
      - c-test

permissions:
  id-token: write
  contents: read

jobs:
  klocwork-codescan:
    runs-on: self-hosted
    steps:

      # Checkout code
      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Print run info
      - name: Print run info
        shell: bash
        run: |
          echo "Ref name is $GITHUB_RUN_ID"
          echo "Source is ${{ github.server_url }}/${{ github.repository }}"
          echo "Subject is $GITHUB_WORKFLOW_REF|${{ github.run_id }}|${{ github.run_attempt }}|${{ github.run_number }}"
          echo "Job is $GITHUB_JOB"
          curl checkip.amazonaws.com

      # Install dependencies on macOS
      - name: Install build dependencies on macOS
        shell: bash
        run: |
          brew update
          brew install cmake openssl@3 make pkg-config
          # Optional: ensure brew binaries are in PATH
          export PATH="/opt/homebrew/bin:$PATH"

      # Run Klocwork scan
      - name: Klocwork scan
        uses: cloudbees-io-gha/perforce-klocwork-sast-publish@v1
        with:
          cloudbees-url: ${{ vars.CLOUDBEES_QA_API_URL }}
          url: ${{ vars.KLOCWORK_URL }}
          token: ${{ secrets.NEW_KLOCWORK_APP_TOKEN }}
          license-host: ${{ vars.KLOCWORK_LICENSE }}
          username: ${{ vars.KLOCWORK_USERNAME }}
          project-name: test-cmake-gha
          build-directory: ctest
          build-tool: make
          build-options: |
            cmake -DCMAKE_USE_OPENSSL=ON -DOPENSSL_ROOT_DIR=/opt/homebrew/opt/openssl@3 .
            make -j14
